version: '2'
services:
  neo4j:
    image: neo4j:3.3.5
    restart: always
    volumes:
      - /data/mysql:/data/mysql
      - /data/pgsql:/data/postgresql
      - /data/maria:/data/mariadb
      - /data/redis:/data/redis
      - /data/memcached:/data/memcached
      - /data/neo4j:/data/neo4j/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/admin
    container_name: neo4j_dev
  mongodb:
    image: mongo:3.7
    restart: always
    container_name: 'mongo_dev'
    volumes:
      - /data/mongo:/data/db
    ports:
      - "27017:27017"
  language-note-client:
    image: tnmk/language-note-client:latest
    container_name: 'language-note-client'
    ports:
      - "8081:8081"
    depends_on:
      - language-note-server
    environment:
      LANGUAGE_NOTE_SERVER_ENDPOINT: ${LANGUAGE_NOTE_SERVER_ENDPOINT}
  language-note-server:
    image: tnmk/language-note-server:latest
    container_name: 'language-note-server'
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - neo4j
    environment:
      MONGO_HOST: ${MONGO_HOST}
      NEO4J_HOST: ${NEO4J_HOST}