version: '2'
services:
  mongodb:
    image: mongo:3.4
    container_name: 'mongo_dev'
    volumes: 
      - /data/db:/data/db
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: 'zookeeper_dev'
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: 'kafka_dev'
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - zookeeper
  neo4j:
    image: neo4j:3.2.2
    volumes:
      - /data/mysql:/data/mysql
      - /data/pgsql:/data/postgresql
      - /data/maria:/data/mariadb
      - /data/redis:/data/redis
      - /data/memcached:/data/memcached
      - /data/neo4j:/data/neo4j/data
    ports:
      - "7474:7474"          
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/admin
    container_name: neo4j_dev      
