# Properties valid for every environment
server:
    servlet-path: /*
    contextPath: /language-note-client
    port : 8081
# Spring boot properties (do not change the keys)
language-note-server:
    endpoint: ${LANGUE_NOTE_SERVER_ENDPOINT:http://localhost:8080/language-note-server}
spring:
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        cache: false
    template:
        cache: false
#spring.mvc.view.prefix=/static/
#spring.mvc.view.suffix=.jsp
#multipart.max-file-size=20Mb
#multipart.max-request-size=20Mb
multipart:
    max-file-size: 20Mb
    max-request-size: 20Mb
